### PR TITLE
feat: added upload files and upload folders icons

### PR DESCRIPTION
**Pull request by dwilt**
Added `Upload-Files` and `Upload-Folders` icons for a new feature I'm working on with Mari.

image

### CODE REVIEW

**Review by kylemh — COMMENTED** [review]
Both of these are missing `fill=“currentColor”`

**Comment by dwilt** [comment]
> Both of these are missing `fill=“currentColor”`

The instructions say "Ensure that the value of either `stroke` or `fill` (there shouldn't be both on one icon) is `"currentColor"`"

Can this be more descriptive? I don't have a `stroke` or `fill` prop in my SVG files (if that's what this is referring to) to change to `"currentColor"`

**Comment by kylemh** [comment]
Feel free to update the instructions.

Your SVG does have a fill. The default fill for an SVG is black. You can either apply the fill attribute to the SVG element itself (to apply it to all child paths) or you can apply a fill color to each path separately. We can tell it doesn't have a stroke because no value is set for the relevant HTML attribute.

So, for this icon, we need to set fill to currentColor so that it's fill match's the parent's `color` value. Otherwise, we'll need to set the icon's fill color manually with every usage.

**Comment by dwilt** [comment]
> Feel free to update the instructions.

I'll do this once I understand what to do

> Your SVG does have a fill. The default fill for an SVG is black. You can either apply the fill attribute to the SVG element itself (to apply it to all child paths) or you can apply a fill color to each path separately. We can tell it doesn't have a stroke because no value is set for the relevant HTML attribute.

I'm no SVG expert so maybe that's why I'm confused. Are you saying I just have to add a `fill="currentColor"` to the root `<svg>` tag? The reason I'm confused is because I don't see a `fill` or `stroke` in either of the files:

**Review by andyhqtran — APPROVED** [review]

**Review by kylemh — APPROVED** [review]

**Pull request merged**
