### PR TITLE
[IT-11] Create Tooltip component

### PR DESCRIPTION
**Pull request by kylemh**
At first I dove into Reach's component, but I would've had to handmake the positioning callbacks it requires to understand where to place the tooltip content - a little TOO low level for my taste.

Instead, I opted to use Radix UI's Tooltip. @andyhqtran and I both love everything Modulz does, and one of the biggest maintainers for ReachUI _also_ built the same, accessible primitive there.

### CODE REVIEW

**Comment by tomaszczura** [comment]
Is it possible to remove this delay when you hover an element?

**Comment by dwilt** [comment]
Code looks good.



There is a bit of opacity in our current ones and we'd probably want to keep it? I'm not sure. Check with the PMs/designers to be sure that the look and feel of this is correct so that the devs won't have to do custom styling and can use this as it is out of the box.

**Review by dwilt — APPROVED** [review]
Code looks solid. Just check with the designers/PMs that this functions/looks the way they'd expect and that it'll replace all of our existing ones.

**Comment by kylemh** [comment]
Design specifically didn't want tooltips to opaque any longer!

**Comment by kylemh** [comment]
@tomaszczura you would need to use manualControlProps in that situation. The default regarding the delay isn't localized to the component. It uses a window event listener to mimic operating system tooltip behavior where after one tooltip is rendered, all of them immediately render when hovering across other items with tooltips.

I couldn't find any accessible library with a prop-level control for this, but also I don't think design will mind the delay? Let me know if you'd like me to write a story showing how to use `manualControlProps` to achieve an immediately rendering tooltip.

**Comment by tomaszczura** [comment]
If design accepts this delay, then we do not have to play with `manualControlProps` to remove it

**Review by rnmp — APPROVED** [review]
Love this. I piggy back @tomaszczura comment about the delay:

I understand that we want to mimic the OS' defaults but the way we use tooltips is a bit more dependent on the text they display.

@tomaszczura @kylemh Perhaps what we do in @AirLabsTeam/next is have a couple of tooltip components with more sensible defaults to our individual usages.

@kylemh 

I would definitely check with @abbyfrankola on opacity options as well as the ability to customize the arrow. I believe making the triangle rounded was preferred by the design team.

**Review by tomaszczura — APPROVED** [review]

**Comment by kylemh** [comment]
I checked with her before embarking on this regarding opacity, so I'm certain it's a constant; however, I didn't ask about the arrow - so I'll await her feedback!

If the delay isn't desired, we can provide an abstraction in here so that somebody can define the delay themselves!

**Comment by kylemh** [comment]
Design feedback within Chromatic link.

**Pull request merged**
