### PR TITLE
Remove modal content Text wrapper

### PR DESCRIPTION
**Pull request by dwilt**
By having this extra element, it breaks potential usages of `display: flex` with their consumers who might be trying to utilize `flex: 1` to get the content to take up the full width of the modal

### CODE REVIEW

**Comment by kylemh** [comment]
I'm fine with removing the element for the sake of flex stylings; however, we should ensure that the ModalContent has this baseline CSS for the text itself.

**Comment by dwilt** [comment]
> I'm fine with removing the element for the sake of flex stylings; however, we should ensure that the ModalContent has this baseline CSS for the text itself.

Why have text styling? So that if someone passes a string, it has some defaults?

**Comment by kylemh** [comment]
Correct. Otherwise everybody will need to import it with each modal usage that has children.

**Comment by dwilt** [comment]
> Correct. Otherwise everybody will need to import it with each modal usage that has children.

I don't think there is anything wrong with that at all. I think it's nice that it's an empty div without styling. Also, FWIW, of all the instances I've seen where we have children inside of a modal (either in `Modal`, `TransactionModal`, or `AnnouncementModal` in the app), it hasn't been text.

**Comment by kylemh** [comment]
Sure, it's been like Formik or a Form. Keep in mind this element has been implicitly applying necessary styles to all of its children (including those elements).

**Review by kylemh — APPROVED** [review]

**Pull request merged**
